name: Miller-Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
        go-version: 1.18

    - name: Build
      run: make build

    - name: Test
      run: make check

    - name: Regression tests
      # We run these with a convoluted path to ensure the tests don't
      # rely on a specific invocation
      run: test/../mlr regtest -S

    - name: PrepareArtifactNonWindows
      if: matrix.os != 'windows-latest'
      run: mkdir -p bin/${{matrix.os}} && cp mlr bin/${{matrix.os}}

    - name: PrepareArtifactWindows
      if: matrix.os == 'windows-latest'
      run: mkdir -p bin/${{matrix.os}} && cp mlr.exe bin/${{matrix.os}}

    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: mlr-${{matrix.os}}
        path: bin/${{matrix.os}}/*
